### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [hschueh/oh_tai_gi#2]
Could I package your app for F-Droid? The firebase deps need to be patched out.

**Comment by hschueh** [comment]
Sure. Please make sure you follow the [license](https://github.com/hschueh/oh_tai_gi/blob/master/LICENSE). (I guess MIT license basically means no restriction). Also keep here updated if it is on F-Droid someday.
Feel free to leave another comment if you need any help.

**Comment by linsui** [comment]
Thanks! I'll update my progress here.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11294 I opened an MR. May I add fastlane in this repo for app metadata?

**Comment by hschueh** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11294 I opened an MR. May I add fastlane in this repo for app metadata?

Sure looks good to me 👍

**Comment by linsui** [comment]
Your app will be available in F-Droid in 1 week. You can put the badge somewhere if you'd like to.

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.gonnaggstudio.oh_tai_gi)

```

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.gonnaggstudio.oh_tai_gi)
```

Thanks!

**Comment by hschueh** [comment]
@linsui cool! One stupid question I'm curious about: what're those prebuilt script doing in F-Droid repo?
```shell
      - sed -i -e '/firebase/d' -e '/admob/d' pubspec.yaml
      - sed -i -e '/firebase/,/version/d' -e '/admob/,/version/d' pubspec.lock
      - sed -i -e 's|maven.fabric.io/public|jitpack.io|' android/build.gradle
      - sed -i -e '/gms/d' -e '/fabric/d' android/build.gradle android/app/build.gradle
      - sed -i -e '/firebase/d' -e '/admob/d' -e '/analytics/d' -e '/Crashlytics/d'
        -e '/if(USE_FIREBASE_ADMOB)/,/}$/d' lib/main.dart
      - sed -i -e '/secret.dart/d' -e '/getAdAppId/,/^}/d' -e '/getBannerAdUnitId/,/^}/d'
        lib/utils/utils.dart
```

**Comment by linsui** [comment]
Those scripts are needed to patch out non free deps. F-Droid doesn't allow non free libs.
